### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by thomasekdahlN** [thomasekdahlN/jeti#1]
![alarm low turbine rpm](https://cloud.githubusercontent.com/assets/26059207/24415858/273dfeda-13e3-11e7-92b5-ad4401d8df2e.png)
![alarm shaft rpm low](https://cloud.githubusercontent.com/assets/26059207/24415859/2740a720-13e3-11e7-9f60-ebc5e7bf4caf.png)
![flight logg - preheat status](https://cloud.githubusercontent.com/assets/26059207/24415857/273beb2c-13e3-11e7-81fc-fb2c122ca378.png)
![status preheat1 x 2](https://cloud.githubusercontent.com/assets/26059207/24415860/27438602-13e3-11e7-8b7e-fb559c49e5e9.png)

**Comment by HABTomas** [comment]
LOOKS GREAT , but try to as visible as possible , during flight you won't have time to study the display !
great work!!!!!!!!!!

**Comment by thomasekdahlN** [comment]
test

**Comment by HABTomas** [comment]
Hej 

Jag ser inget :o)

MVH 

 

Tomas

HAB Electronic AB

Sadelvägen 5

34140 Ljungby

www.hab.se

+46(0)372-80444

 

Från: thomasekdahlN [mailto:notifications@github.com] 
Skickat: söndag den 14 maj 2017 15:14
Till: thomasekdahlN/jeti
Kopia: HABTomas; Comment
Ämne: Re: [thomasekdahlN/jeti] Screenshots (#1)

 

test

**Comment by thomasekdahlN** [comment]
Assuming you tested the newest ecu_16.lc script.


Could you take a screen dump of the error log.

Under the Applications menu, (not in the app), on the left bottom icon (tool icon), click on that and you get a log with error messages. Take a picture of the messages and send to me.

Thank you. 


Thomas Ekdahl
Privat mail
Skype: thomasekdahl
Mobile : +47 911 43 630

**Comment by HABTomas** [comment]
Hello 

I have not bee folowing this

I have still DS16 so it is not for me or??

MVH 

 

Tomas

HAB Electronic AB

Sadelvägen 5

34140 Ljungby

www.hab.se

+46(0)372-80444

 

Från: thomasekdahlN [mailto:notifications@github.com] 
Skickat: måndag den 15 maj 2017 08:36
Till: thomasekdahlN/jeti
Kopia: HABTomas; Comment
Ämne: Re: [thomasekdahlN/jeti] Screenshots (#1)

 

Assuming you tested the newest ecu_16.lc script.


Could you take a screen dump of the error log.

Under the Applications menu, (not in the app), on the left bottom icon (tool icon), click on that and you get a log with error messages. Take a picture of the messages and send to me.

Thank you. 


Thomas Ekdahl
Privat mail
Skype: thomasekdahl
Mobile : +47 911 43 630

**Comment by thomasekdahlN** [comment]
Got an email from you this morning, strange………..

You can try the ecu_16.lc - it runs on DS16 (But it seems like som of the configs have bug, but give me a screendump of the log if it does not work, and it looks possible to fix)



Thomas Ekdahl
Privat mail
Skype: thomasekdahl
Mobile : +47 911 43 630
