### ISSUE TITLE
ds14 supported?

### ISSUE THREAD

**Issue by natxopedreira** [thomasekdahlN/jeti#12]
Hello Thomas

Do you know if this will work on a ds14 (first gen)? I'm asking before ordering the xicoy telemetry adapter

Regards,
Jose

**Comment by thomasekdahlN** [comment]
If you run the ecu_16 file as the lua script, not the ecu lua script it is intended for first generation Jeti with lower memory. Its a bit less tuneable (to save memory), but it has the same basics. It worked on my first gen DS16.

**Comment by natxopedreira** [comment]
Hello Thomas

My adapter arrived so i installed the app using the jeti studio wizzard, it only added the file "ecu" not "ecu_16" so i manually copied that file to the correspond sd card folder.

Then i went to ecu dashboard to configure, choose xicoy sensor. 

In ECU sensor turbine left i get an value called "Turbine" and as soon as i selected it i get a console error, took a photo 
[https://imgur.com/b4IPs1q](https://imgur.com/b4IPs1q)

Attemp to index a number value.... looks like something went out of bounds
