### ISSUE TITLE
ECU lua app Error

### ISSUE THREAD

**Issue by CapiLara** [thomasekdahlN/jeti#6]
Hi Thomas 
I get the message error
![ECU ERROR](https://user-images.githubusercontent.com/66392878/160332186-ddff783b-336a-4f22-8423-f53f05e969db.png)
selecting the ecu type  ( Kingtech ) and the lua app crash, using vspeak telemetry converter .  any help thanks

**Comment by HABTomas** [comment]
what gear do you have??
28 mars 2022 07:31:38 +02:00, skrev CapiLara ***@***.***>:

**Comment by CapiLara** [comment]
kingtech K260 g4 and Vspeak telemetry converter !!!!!

**Comment by thomasekdahlN** [comment]
I will check if I see any errors (later), it could be as simple as a malformed json config file for your turbine.

**Comment by thomasekdahlN** [comment]
It was a syntax error in the Kingtech json config file, it is solved. If you donload the lua app from this repo it should work. I will send a fix to Jeti App store later.
